### ISSUE TITLE
Setup Deployment ENV

### ISSUE THREAD

**Issue by aminlatifi** [GeneralMagicio/QAcc-BE#7]
- [x] Prepare deployment server
- [x] Prepare Database (With Devops)
- [x] Update github actions
- [x] Prepare Redis Server

**Comment by aminlatifi** [comment]
@mhmdksh Note, it must be able to communicate with authentication server

**Comment by Rolazo** [comment]
@aminlatifi  please assignee to me this issue. I couldn't since GM Digital Ocean account has MFA. Once is disable this will be completed by tomorrow <3

**Comment by aminlatifi** [comment]
@Rolazo  @mhmdksh Please add secrets needed for the test pipeline, like what we have in the impact-graph.

**Comment by mhmdksh** [comment]
Closing this, This has been done!
